### ISSUE TITLE
cannot import name 'cached_property' from 'werkzeug'

### ISSUE THREAD

**Issue by bill-uncultured** [jarus/flask-testing#143]
werkzeug just released 1.0.0, and the deprecated werkzeug.cached_property has been removed in favor of werkzeug.utils.cached_property.

This was addressed in October by pull request # 141, but it seems like it failed testing because the old python 3.3 and 2.6 couldn't be downloaded.

```
/usr/lib/python3.7/site-packages/flask_testing/__init__.py:13: in <module>
    from .utils import TestCase, LiveServerTestCase
/usr/lib/python3.7/site-packages/flask_testing/utils.py:35: in <module>
    from werkzeug import cached_property
E   ImportError: cannot import name 'cached_property' from 'werkzeug' (/usr/lib/python3.7/site-packages/werkzeug/__init__.py)
```

**Comment by teapow** [comment]
Same issue as: https://github.com/noirbizarre/flask-restplus/issues/777

The proposed temporary solution is to pin `Werkzeug==0.16.1` until a proper fix is put in place.

**Comment by erodrig** [comment]
I have created a fix for this https://github.com/jarus/flask-testing/pull/144 

but CI infrastructure is not working 

Downloading archive: https://storage.googleapis.com/travis-ci-language-archives/python/binaries/ubuntu/16.04/x86_64/python-2.6.tar.bz2
0.10s$ curl -sSf --retry 5 -o python-2.6.tar.bz2 ${archive_url}
curl: (22) The requested URL returned error: 404 Not Found

**Comment by Ri1a** [comment]
Another fix would be to edit the `flask_testing/utils.py` on line 29:
`from werkzeug.utils import cached_property`
 instead of 
`from werkzeug import cached_property`

**Comment by elgohr** [comment]
Any updates regarding CI?

**Comment by Sispheor** [comment]
As it is fixed. Could you release a new version? :)

**Comment by Rahulrao0786** [comment]
from werkzeug import cached_property
ImportError: cannot import name 'cached_property' from 'werkzeug' (C:\Users\BABA\PycharmProjects\Automation\venv\lib\site-packages\werkzeug\__init__.py)


I am getting this error message

**Comment by Rahulrao0786** [comment]
from flask import Flask
from flask_restplus import Api, Resource
from werkzeug.utils import *

app = Flask(__name__)
api = Api(app)


@api.route('/language')
class Language:
    def __get__(self):
        return {'hey': 'there'}


if __name__ == "__main__":
    app.run(debug=True)

**Comment by vicmunoz** [comment]
I've fixed this with:
`import werkzeug
werkzeug.cached_property = werkzeug.utils.cached_property`

**Comment by KareenaR** [comment]
> I've fixed this with:
> `import werkzeug`
> `werkzeug.cached_property = werkzeug.utils.cached_property`

Thanks! This works.

**Comment by jnozsc** [comment]
fyi: this issue has been fixed in version `0.8.0`

**Comment by evertoncastro** [comment]
Updating to Werkzeug==0.16.1 has fixed.

**Comment by mumapada** [comment]
Changed  lib\site-packages\flask_restx\api.py", line 28, in <module>
    from werkzeug import cached_property as below :
---------------------------------------------------
#from werkzeug import cached_property
from werkzeug.utils import cached_property

**Comment by felixminom** [comment]
Still happening when upgrading to 1.0.1 version

**Comment by philipperemy** [comment]
Still happening as of today.

**Comment by SidJain1412** [comment]
Still broken with werkzeug==1.0.1 as of 4th Sept 2020

Can be fixed by adding 
```
import werkzeug
werkzeug.cached_property = werkzeug.utils.cached_property
```
before importing flask_restplus

**Comment by ctwardy** [comment]
Thanks @SidJain1412!  

User-side workaround when not expecting to call werkzeug directly:
```python
try:
    from flask_restplus import Resource, Api
except ImportError:
    import werkzeug
    werkzeug.cached_property = werkzeug.utils.cached_property
    from flask_restplus import Resource, Api
```

**Comment by JosephHubbard** [comment]
This is still an issue.
My API backend still fails when using untampered Flask due to "cannot import name 'cached_property' from 'werkzeug'".

**Comment by bharath-kumarn** [comment]
This is still an issue.



ontology_1  |   File "./get_title_details.py", line 1, in <module>
ontology_1  |     from robobrowser import RoboBrowser
ontology_1  |   File "/usr/local/lib/python3.6/site-packages/robobrowser/__init__.py", line 3, in <module>
ontology_1  |     from .browser import RoboBrowser
ontology_1  |   File "/usr/local/lib/python3.6/site-packages/robobrowser/browser.py", line 8, in <module>
ontology_1  |     from werkzeug import cached_property
ontology_1  | ImportError: cannot import name 'cached_property'

**Comment by paulakeen** [comment]
If I downgrade to Werkzeug==0.16.1 I get this other error:
from werkzeug.local import ContextVar
ImportError: cannot import name 'ContextVar' from 'werkzeug.local' (/home/paula/venvs/bidlab-venv/lib/python3.8/site-packages/werkzeug/local.py)

**Comment by ritesh-hubbler** [comment]
Werkzeug==2.0.1
Flask==2.0.1
flask-restplus==0.13.0

With this requirements, the issue is still there, I downgraded to
Werkzeug == 1.16.1 and downgraded other dependencies too... so it worked, but it should be working with latest version too, so please release a new version with this fix.

**Comment by rafael-andrade** [comment]
> Werkzeug==2.0.1
> Flask==2.0.1
> flask-restplus==0.13.0
> 
> With this requirements, the issue is still there, I downgraded to
> Werkzeug == 1.16.1 and downgraded other dependencies too... so it worked, but it should be working with latest version too, so please release a new version with this fix.

When I downgrade it says: **flask 2.0.1 requires Werkzeug>=2.0, but you'll have werkzeug 0.16.1 which is incompatible.**. Any suggestions?

**Comment by ipam73** [comment]
+1 Any ideas on how to resolve this? Haven't been able to solve the issue with the responses above and downgrading is not an option due to flask 2.0.1 not being compatible.

> Flask==2.0.1
> Flask-RESTful==0.3.9
> Flask-Testing==0.7.1
> Werkzeug==2.0.1

Traceback:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/unittest/loader.py", line 434, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/lib/python3.7/unittest/loader.py", line 375, in _get_module_from_name
    __import__(name)
  File "/usr/src/app/project/tests/test_account_model.py", line 6, in <module>
    from project.tests.base import BaseTestCase
  File "/usr/src/app/project/tests/base.py", line 4, in <module>
    from flask_testing import TestCase
  File "/usr/local/lib/python3.7/site-packages/flask_testing/__init__.py", line 13, in <module>
    from .utils import TestCase, LiveServerTestCase
  File "/usr/local/lib/python3.7/site-packages/flask_testing/utils.py", line 35, in <module>
    from werkzeug import cached_property
ImportError: cannot import name 'cached_property' from 'werkzeug' (/usr/local/lib/python3.7/site-packages/werkzeug/__init__.py)
```

**Comment by toddman2** [comment]
> If I downgrade to Werkzeug==0.16.1 I get this other error:
> from werkzeug.local import ContextVar
> ImportError: cannot import name 'ContextVar' from 'werkzeug.local' (/home/paula/venvs/bidlab-venv/lib/python3.8/site-packages/werkzeug/local.py)

100%.  I can't believe this is still going on.

**Comment by bharath-kumarn** [comment]
Yes

**Comment by palmettobugz** [comment]
Maybe related:    Switch locals to be based on ContextVars #1778
[    https://github.com/pallets/werkzeug/pull/1778
](    https://github.com/pallets/werkzeug/pull/1778
)
pgjones commented on Mar 28, 2020 • 
ContextVar was introduced in Python 3.7 and is effectively the same as Local in Werkzeug (although a different API). They should work in Greenlet and threading contexts as before but also now in asyncio or other async/await contexts.

The __storage__ attribute has been kept for backwards compatibility (even though it is a dunder it seems it is used, e.g. in tests).

The ident_func though must be deprecated as this is now handled by the ContextVar. This may cause some backwards incompatibility.

**Comment by andrescevp** [comment]
here same problem:

req:

```
psycopg2==2.8.6
SQLAlchemy==1.4.3
WTForms==2.3.3
openapi_schema_validator==0.1.5
requests==2.25.1
inflect==5.3.0
openapi_spec_validator==0.3.0
Flask==2.0.1
Flask_Cors==3.0.9
slug==2.0
WTForms_JSON==0.3.3
Flask_RESTful==0.3.9
mergedeep==1.3.4
six==1.15.0
flask_request_id_header==0.1.1
PyPika==0.48.0
simplejson==3.17.3
PyYAML==5.4.1
flask-apispec==0.11.0
flask_restplus==0.13.0
```

**Comment by 4vadim4** [comment]
Is there a solution to this problem?
Because the first mention with _Flask==2.0.1, flask-restplus==0.13.0, Werkzeug==2.0.1_ was in June.
This bug has yet to be resolved?

**Comment by nise** [comment]
Any updates here?

**Comment by Ninthpool** [comment]
The issue still persists as of today... temporary workaround:
```python
try: 
    from flask_restplus import Api, Resource
except ImportError:
    import werkzeug, flask.scaffold
    werkzeug.cached_property = werkzeug.utils.cached_property
    flask.helpers._endpoint_from_view_func = flask.scaffold._endpoint_from_view_func
    from flask_restplus import Api, Resource
```

**Comment by vikramadhav** [comment]
Current requirements.txt 

```
Flask==2.1.2
Flask-Assets==2.0
flask-restplus==0.13.0
Werkzeug==2.1.2
```

and applied work around as (Downgrade is not possible due to compatibility)



```
try: 
    from flask_restplus import Api, Resource,Namespace
except ImportError:
    import werkzeug, flask.scaffold
    werkzeug.cached_property = werkzeug.utils.cached_property
    flask.helpers._endpoint_from_view_func = flask.scaffold._endpoint_from_view_func
    from flask_restplus import Api, Resource,Namespace
    
from models.hello_world import helloWork

data_edits_namespce=Namespace('data_edits')

data_edits_namespce.add_model('HelloWorld',helloWork)
```

Now the exception is coming 

```
from flask_restplus import Api, Resource,Namespace
venv/lib/python3.10/site-packages/flask_restplus/model.py", line 8, in <module> from collections import OrderedDict, MutableMapping
ImportError: cannot import name 'MutableMapping' from 'collections' (/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/collections/__init__.py)
```


Not sure what i am missing here , does any one else also faced same issue

**Comment by felixminom** [comment]
We all should be migrating to flask-restx which is a wrapper for this library and it's been actively maintained.

**Comment by toddman2** [comment]
Clearly seems the owner is busy these days or no longer has an interest in fixing this.  I'm cutting the guy some slack -- it's been a useful package so far.  It would be appreciated if he could check in with us one way or another.  Thanks for all your time you've put into so far.

**Comment by DanniBot** [comment]
> 

This solution works for me. Thanks!

**Comment by fauber5** [comment]
"
#0 370.1 ERROR: Cannot install -r requirements.txt (line 32) and Werkzeug==0.16.1 because these package versions have conflicting dependencies.
#0 370.1
#0 370.1 The conflict is caused by:
#0 370.1     The user requested Werkzeug==0.16.1
#0 370.1     flask 2.0.2 depends on Werkzeug>=2.0

 The temporary solution isn't possible.  "pin Werkzeug==0.16.1 until a proper fix is put in place."
